### PR TITLE
Implemented the ShiftLogger

### PR DESCRIPTION
**Pull request by ukpagrace**

### CODE REVIEW

**Comment by stevietv** [comment]
hey @ukpagrace - thanks for the submission. Great work! This all seems to be working as it should. 

I would say that the UI does present the results a bid oddly, with boxes around some items. was that intentional?

image

in any case, approved! ✅

**Comment by ukpagrace** [comment]
Yes, it was intentional. 
Just trying a different look.

What of the code is it okay?

**Comment by stevietv** [comment]
> What of the code is it okay?

absolutely! it was great. I'd have only a couple of suggestions:

* there are 3 unnecessary usings in menu.cs:
```
using System;
using System.Linq;
using System.Threading.Tasks;
```
* I'd suggest building your connectionstring into the appsettings.json instead of program.cs - its better for real apps later on

**Comment by ukpagrace** [comment]
I will make that a habit 

Thank you

**Pull request merged**
