### PR TITLE
Project is done!

### PR DESCRIPTION
**Pull request by Forser**
WebAPI + Console are working against a MSSQL DB.
CRUD supported.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Forser I've recently added a requirement in the project for the front-end to handle exceptions. Example, if the web api isn't working, I get this: 
image

image

Could you please add that?

**Comment by Forser** [comment]
Will fix that, must been blind/tired at the moment and missed it.

**Comment by Forser** [comment]
Noticed an error, trying to sort it out.

**Comment by Forser** [comment]
Error handling should be working better now.

**Comment by Forser** [comment]
Error handling should be working better now.

**Pull request merged**
