### PR TITLE
Shift Logger

### PR DESCRIPTION
**Pull request by adityavaidya108**

### CODE REVIEW

**Comment by kimfom01** [comment]
Hey @adityavaidya108 could you take a look at you r migrations? It seems like it is empty and the database table are not being created.

Please fix that so that I can complete your review :pray:

**Comment by adityavaidya108** [comment]
Hey @kimfom01  , I took a look and fixed the issue with the migrations. The database tables should now be created correctly. Let me know if you encounter any further issues, and thanks for reviewing! 🙏

**Review by kimfom01 — CHANGES_REQUESTED** [review]
@adityavaidya108  I was finally able to execute your code. I have some notes that I will like you to address before I can approve your pull request :rocket: 

Separation of Concerns in App.cs

- Move methods that call api to their own class (Get, Put, Post, Delete Workers/Shifts)
- The GetSelectionAsync method is doing a lot of things. Is there a way you can extract the logic into methods to enhance maintainability and readability?

Lean Controller Approach

- Move controller logic to service layer and inject service into controller to make your API controller "lean"
image


Good luck and if you have any questions feel free to ask! :saluting_face:

**Comment by adityavaidya108** [comment]
@kimfom01 I have tried Separation of Concerns this time. Can you please check

**Review by kimfom01 — APPROVED** [review]
Your code base looks better structured now and functionality works so I will approve the PR. I noticed that you didn't move the controller logic to a separate service to make your API controller "lean". There isn't any serious logic happening in the controller so I understand but it's best to follow all the requirements :wink: that's why they are called requirements sir


Good luck with your future projects :confetti_ball:

**Pull request merged**
