### PR TITLE
initial submission

### PR DESCRIPTION
**Pull request by frockett**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@frockett Well done! Thanks for submitting. I'm getting this when trying to add an employee. You can add a null check before calling Any(). 

image

**Comment by frockett** [comment]
Thanks, got it!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@frockett Almost there! It looks like there's something not quite right when the end date validation doesn't pass. The time that ends up added isn't the one that I actually input. Could you please check?
image

**Comment by frockett** [comment]
@TheCSharpAcademy Okay I think I got it. shiftStart was accidentally being assigned twice AND I had used an if statement instead of while. Here's the validation loop: 
image

Hopefully this fixes it. 
image

Thanks for the reviews! It's amazing the little things you can miss when you're working alone. I should get better at testing everything more thoroughly.

**Pull request merged**
