### PR TITLE
Fixed code check errors

### PR DESCRIPTION
**Pull request by Speedierone**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Speedierone Well done! The project looks good.

One requirement is being met though. End date should never be before start date:
image

Also, what's the purpose of this file? 
image

**Comment by Speedierone** [comment]
No problem i will look into getting that corrected. That class is meant to store the path to where the database is being created but i think im going to remove it and just hardcode it in.

**Comment by Speedierone** [comment]
@TheCSharpAcademy i have now fixed the issues :)

**Comment by TheCSharpAcademy** [comment]
@Speedierone Not exactly what I was expecting, but I guess your solution is elegant 😆 I was expecting some sort of validation with a message to the user saying what's happening. But ok, I'll let it pass 😆😆

**Pull request merged**
