### PR TITLE
Requested Changes?

### PR DESCRIPTION
**Pull request by ManuelE-Osorio**
Sorry for the delay. I've added a DBInit() and changed the name of some controllers to services/helpers according to the requested changes. Still not sure if I am using the structure correctly, but I'm studying right now the Repository Model.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@ManuelE-Osorio I was able to run the project but now I'm getting this:
image

Do I need to manually insert an employee to the DB?

**Comment by ManuelE-Osorio** [comment]
Helllo @TheCSharpAcademy  I've added a PopulateDB method in the latest commit. You can test with ID 1 to 20

**Comment by TheCSharpAcademy** [comment]
@ManuelE-Osorio Very nice! ✅✅

I think I'd have put the AddShift logic in its own end point, though. Having it in putshift is a bit misleading. What was the thought process?

**Comment by ManuelE-Osorio** [comment]
I suppose the idea was to have a controller for each model. When you say in its own end point, do you mean having a controller for AddShift or using a different route?

**Pull request merged**
