### PR TITLE
Done

### PR DESCRIPTION
**Pull request by kronyer**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kronyer Fala doutor! For a better UX, it would be good to inform the user that they need to have at least one worker before starting a shift, otherwise the app crashes. 

image

**Comment by kronyer** [comment]
I think I've done it! Also, I've changed the Begin and Start method to Patch, because I think it's more correct? At least that's what I understood

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kronyer Everything looks good, there's just one more thing. If I stop running the API and try calling it from the front-end, the error is handled and the app keeps running, but no error message is displayed to the user. Could you please add that?

**Comment by TheCSharpAcademy** [comment]
@kronyer Closing the PR for admin purposes but feel free to reopen when you're ready 😎

**Pull request closed without merging**
