### PR TITLE
Shift Logger WEB API

### PR DESCRIPTION
**Pull request by lonchanick**
Hello everyone, this is my Shift logger web api

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@lonchanick Hey there! Well done, it's looking great. Just a couple of issues:

1 - At the moment the dates aren't being logged in properly:
image

2 - When I choose checkout, nothing happens. I can only add a checkout by choosing check in, a worker ID and then choosing check out

3 - This isn't a requirement, but it would be good to clear the screen after an operation, for better readability: 
image

4 - Unless this is inheriting from an interface, you don't need to leave unused code: 
image

**Comment by lonchanick** [comment]
Nice! 
I'm working on!

**Comment by lonchanick** [comment]
Hey Pablo!
Thanks!
Everything is done!
Regards! 

Oh, It is Owe*

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@lonchanick Very good, you're close!
One issue though, I can have multiple shifts going on at the same time with the same worker. That's a big issue with the business logic. You can't let that happen:

image

Also, get rid of any unused code:

image


image


image


image

**Comment by TheCSharpAcademy** [comment]
@lonchanick Let me know if you need help 😁

**Comment by lonchanick** [comment]
Hey Pablo, thanks!
Sadly I only have weekends to programming, and I have been thinking in this and nothing occurs to me, how would you solve this requirement? Any clue for me? 😅

**Comment by TheCSharpAcademy** [comment]
> Hey Pablo, thanks! Sadly I only have weekends to programming, and I have been thinking in this and nothing occurs to me, how would you solve this requirement? Any clue for me? 😅

@lonchanick Check on the database if worker has ongoing shift. If they have, let the user know and don't let a record be inserted. 😎

**Comment by lonchanick** [comment]
Hey Pablo!
Homework is done!

Regards!

**Pull request merged**
