### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by mariusgrHiof**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@mariusgrHiof Thanks for submitting! 😊
Currently I'm unable to create a record because I don't know what's expected: 

image

Also, it would be good to say "enter a start date" and "enter an end date" and return a specific message when they input an end earlier than a start. 😊

**Comment by mariusgrHiof** [comment]
@TheCSharpAcademy Thanks for the review! I'll look at it and make some changes!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@mariusgrHiof Sorry about the delay. The review should move faster from now. How do I add a worker? 

image

**Comment by mariusgrHiof** [comment]
@TheCSharpAcademy No worries! I'm not sure what happend but my changes created a new pr with new link: https://github.com/TheCSharpAcademy/CodeReviews.Console.ShiftsLogger/pull/18

**Pull request closed without merging**
