### PR TITLE
Shifts Logger completed

### PR DESCRIPTION
**Pull request by lawangGurung**
I enjoyed creating WEB/API and using it in a console app.  Thank you for taking the time to review my code.

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @lawangGurung  - thanks for the submission on this project. Its doing everything it should but I do have one thing that I need you to fix up before it can be approved:

* currently you have a separate solution file for each project.You should instead have one solution file linking both projects. you would do that by opening your main solution for the webAPI, and then adding the existing project file for the console app to it. Its the intention that a program (made of multiple project) has one solution file to build.

Something else that you might consider in the future - allow a user to enter a start and end date, so that you can validate that the end of shift time isn't BEFORE the start of shift time.

**Comment by lawangGurung** [comment]
I deleted the rest of the solution file except the web API one.

**Review by lawangGurung — COMMENTED** [review]
I deleted the rest of the solution file except the one in the web API.

**Comment by stevietv** [comment]
this works, ideally your solution file would be in the head folder and not in the subfolder for webapi though.

anyway, congrats! approved ✅

**Pull request merged**
