### PR TITLE
done

### PR DESCRIPTION
**Pull request by kwm0304**

### CODE REVIEW

**Comment by kwm0304** [comment]
codacy issues are for commented out mock class that would run on start if uncommented

**Comment by stevietv** [comment]
hi @kwm0304 - thanks for the submission. Overall seems like a well thought out and detailed project, lots of complexity added, however there are a few places however where I'm encountering crashes/errors and issues

* trying to view shifts when none are created causes a nullexception
* Viewing late employees on a started shift when there are none causes an JsonException in `GetLateEmployees`
* how to I actually clock in as an employee onto a shift? Can you explain?
* Theres no handling in the client of a non-running API also causing a connection error

**Comment by kwm0304** [comment]
@stevietv hey, can you look at this again when you get a chance

**Comment by stevietv** [comment]
Just to summarise what we discussed on discord:

- you interpreted the project as more a management tool instead a tool for employees to log in and out of shifts (i.e. record their worked hours)
- That's fine as its not necessarily against the requirements of the project, here you are intended to learn about WebAPI and interaction with them via a front end.
- there is one requirement you still need to work into the project:
  - Your front-end project needs to have try-catch blocks around the API calls so it handles unexpected errors (i.e. the API isn't running or returns a 500 error.)

**Comment by stevietv** [comment]
thanks for adding the try-catch error handling. with that the project is APPROVED! ✅

**Pull request merged**
