### PR TITLE
Finished Project

### PR DESCRIPTION
**Pull request by Deviationlark**
this was a tough one

### CODE REVIEW

**Comment by Doc415** [comment]
Hey there nice to see this one completed.  
It is working fine, yet backend  is missing a service layer that is a requirement in this project. :<
image

Your code is neat so it wont take more than few minutes to add a service layer.

**Review by Doc415 — CHANGES_REQUESTED** [review]
Needs a service layer in backend as it is a requirement

**Comment by Deviationlark** [comment]
I added the service layer and added some more validation. Wasn't sure what a service layer needs to have but i figured it out with chatGpt, if its incorrect feel free to let me know :D

**Comment by Doc415** [comment]
Nice work. Congrats on your yellow belt.

**Review by Doc415 — APPROVED** [review]

**Pull request closed without merging**
